name: Build EXE (C++)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      # MinGW-w64 설치 및 PATH 설정
      - name: Setup MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      # g++로 컴파일 (이제 g++을 바로 사용 가능)
      - name: Compile
        run: g++ -static -o MouseTracker.exe main.cpp -lgdi32 -Wl,-subsystem,windows

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MouseTracker
          path: ./MouseTracker.exe
